### ISSUE TITLE
Dataset and Tracker Release Date

### ISSUE THREAD

**Issue by HamadYA** [NorahGreen/CiteTracker#1]
Hi,
Thanks for your amazing work.

When are you going to release your work related codes and data, if I may ask?

Thanks

**Comment by BasitAlawode** [comment]
@HamadYA , interesting work indeed.
@NorahGreen, I am interested in the codes and trained models as well.

Thanks.

**Comment by NorahGreen** [comment]
I will release it as soon as possible.

**Comment by 201722111112027** [comment]
> I will release it as soon as possible.

Hi, will the code be open sourced in the near future?

**Comment by NorahGreen** [comment]
Yes, I will release them soon. Sorry for waiting so long.
